### ISSUE TITLE
How to receive IP in client

### ISSUE THREAD

**Issue by NgKhanh** [pbojinov/request-ip#17]
Hello. I'm working a Reactjs project. And in my understanding, this module reture IP on server, how to receive ip on client? Regards

**Comment by pbojinov** [comment]
@NgKhanh unfortunately there's no way to retrieve a user's IP on the client without pinging some server. Hence here's two possible solutions:

1. Use one of the many free services that provides IP lookup and ping that service from your client-side react.js app. E.g. https://jsbin.com/ketopih/edit?js,console

2. Host your own IP address lookup by using `request-ip` on the server and pinging this server from your client. 

Hope that helps.
