### ISSUE TITLE
Support Cloudflare?

### ISSUE THREAD

**Issue by fluxsauce** [pbojinov/request-ip#20]
https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-

> **First exception: CF-Connecting-IP**
>
> To provide the client (visitor) IP address for every request to the origin, Cloudflare adds the CF-Connecting-IP header.
>
> "CF-Connecting-IP: A.B.C.D"
>
> where A.B.C.D is the client's IP address, also known as the original visitor IP address.

and

> **Sixth Exception: True-Client-IP**   Enterprise Plan only
> 
> To provide the client (visitor) IP address for every request to the origin, Cloudflare adds the True-Client-IP header.
> 
> "True-Client-IP: A.B.C.D"
> 
> where A.B.C.D is the client's IP address, also known as the original visitor IP address. This request header is only available on our Enterprise plan.

If you're willing, I can submit a PR.

**Comment by pbojinov** [comment]
PR would be wonderful! Thank you

**Comment by fluxsauce** [comment]
Cool, can do. Is there anything blocking https://github.com/pbojinov/request-ip/pull/19 ? If so, I'd rather build on that one to avoid a potential merge conflict.

**Comment by pbojinov** [comment]
Nothing blocking #19. 

I'll go ahead and merge that into master after I finish running some tests. 

Feel free to build off that.
