### ISSUE TITLE
ES2015 Support

### ISSUE THREAD

**Issue by pbojinov** [pbojinov/request-ip#22]
As more of us start adopting ES6/ES2015 in node, we should think about re-writing the library to fit the modern landscape.

Here's the Node.js ES2015 Support: http://node.green/

What are you thoughts on having an ES2015 version and a backwards compatible ES5 version compiled with babel?

**Comment by fluxsauce** [comment]
Working on it :-)

**Comment by pbojinov** [comment]
Great job @fluxsauce!
