### ISSUE TITLE
Allow using node > 6

### ISSUE THREAD

**Issue by akaNightmare** [pbojinov/request-ip#27]
Hello, I have an error when trying to install this package, please remove this line https://github.com/pbojinov/request-ip/blob/master/package.json#L57

**Comment by pbojinov** [comment]
What version of node are you using @akaNightmare?

**Comment by pbojinov** [comment]
Just want to be able to test it before deploying fix.

**Comment by akaNightmare** [comment]
@pbojinov 7.10.0

**Comment by akaNightmare** [comment]
@pbojinov any news?

**Comment by pbojinov** [comment]
Fixed in latest release `2.0.2`. @akaNightmare can you please try to reinstall?

**Comment by akaNightmare** [comment]
@pbojinov thanks, everything is ok.
