### ISSUE TITLE
Not getting the right ip first time

### ISSUE THREAD

**Issue by glanceded** [pbojinov/request-ip#28]
Hi there

Something wired is happening and I can't get it what.
The case: 
I'm making a request to a nodejs http-proxy server and when the first request is made from the client, I'm getting ::1 as ip.
When I'm making the second request I get ::ffff:127.0.0.1.
When I'm making a request without a proxy, I'm getting all the time ::ffff:127.0.0.1
Is there something that i should know?

Thanks

**Comment by pbojinov** [comment]
I'm not sure what's going on there. Can you provide a link to some code to reproduce the issue?

**Comment by pbojinov** [comment]
Going to close this for now, can re-open once we have more info.
