### ISSUE TITLE
All my ips looks like `::ffff:127.0.0.1`

### ISSUE THREAD

**Issue by hackhat** [pbojinov/request-ip#31]
Is there a problem?

I use it like this `const ip = requestIp.getClientIp(req);`

thanks

**Comment by awaisabir** [comment]
Might be because you are using it locally?

**Comment by hackhat** [comment]
I'm using on EC2 amazon

**Comment by natcohen** [comment]
Having the same problem... I think it's because we're using a proxy (nginx in my case)

**Comment by pbojinov** [comment]
Can you guys please provide some more info on the whole stack and platform that you are using?

That way we can try to replicate the issues.

**Comment by nithi2023** [comment]
I am on Scaleway VPS with HAProxy on port 80..

**Comment by hackhat** [comment]
I think was docker

**Comment by austince** [comment]
There are also some issues depending on the specific Gateway / Loader Balancer setup. I think we need some more configuration options as mentioned in other issues.

**Comment by nimatullah** [comment]
I have the same Issue, sometimes it does not get correct IP
![ip](https://user-images.githubusercontent.com/3712526/41849113-0b735fe8-7895-11e8-84ef-3f474781d451.png)

**Comment by austince** [comment]
I can put in a PR as soon as we discuss how we want to solve it!

**Comment by nimatullah** [comment]
Ok

**Comment by abusada** [comment]
I use it with [ipaddr.js](https://github.com/whitequark/ipaddr.js/blob/master/README.md#global-methods) like this 

```
const ip = ipaddr
			.process(requestIp.getClientIp(req))
			.octets.join('.');
```

to get the right ip address

**Comment by artofspeed** [comment]
how about ipv6 @abusada ?
