### ISSUE TITLE
Client IP not getting captured 

### ISSUE THREAD

**Issue by deepanigi** [pbojinov/request-ip#36]
I am using the below code within my node js application and when i try to run it locally the  code inside app.use is not getting triggered and ip variable is blank
```
var connect = require('connect');
var http = require('http');
app.use(requestIp.mw())
var ip
app.use(function(req, res) {
    // by default, the ip address will be set on the `clientIp` attribute
     ip = req.clientIp;
     res.end(ip + '\n');
    console.log('ip is %s',ip)
   
});
```

**Comment by DonteRavae** [comment]
I think your issue may be you never required the "request-id" module before trying to implement it as middleware.

**Comment by pbojinov** [comment]
@deepanigi does requiring the module in the in the top of the file solve this problem for you?
