### ISSUE TITLE
Add support for fastify

### ISSUE THREAD

**Issue by bradennapier** [pbojinov/request-ip#41]
At the moment you will always get `null` from fastify unless one of the headers match.  Fastify puts most of the data you are looking for in `raw`, so my current workaround is to do the following, which is not ideal, but seems to work:

```
requestIP.getClientIp(request) ||
requestIP.getClientIp(request.raw)
```

So should be a simple addition to allow for this.

**Comment by marcuspoehls** [comment]
@bradennapier Hey Braden, just a heads up.

I created a [request-ip](https://github.com/supercharge/request-ip) package supporting Fastify.

I was using this `request-ip` package for my hapi.js plugins. Now I switched to my own package to retrieve a request’s IP address.

**Comment by pbojinov** [comment]
@marcuspoehls sorry for the delay. I wasn’t getting these notifications via email due to some spam filters. Those should be cleared up now.

I’m happy to get some of these new changes merged in this week. Will review and get back shortly.
