### ISSUE TITLE
Wrong Client Ip address been picked in your recent version

### ISSUE THREAD

**Issue by stevonjugush** [pbojinov/request-ip#57]
According to this documentation ([x-forwarded-for](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For)), the order of ip addresses in the x-forwarded-for header is:

`X-Forwarded-For: <client>, <proxy1>, <proxy2> `

From your documentation, you have highlighted that you pick the last one which conflicts with where the client ip is
<img width="863" alt="image" src="https://user-images.githubusercontent.com/54135096/172583856-146ff713-bdac-4c53-a160-4e33508ca896.png">

**Comment by sidan5** [comment]
This duplicates [https://github.com/pbojinov/request-ip/issues/60](url)

**Comment by pbojinov** [comment]
Thank you for your patience all and sorry about that!

Fixed in v3.0.1 that was just released.

**Comment by stevonjugush** [comment]
Thanks @pbojinov.
