### ISSUE TITLE
Bad extract ip from x-forwarded-for

### ISSUE THREAD

**Issue by masak64** [pbojinov/request-ip#60]
in commit https://github.com/pbojinov/request-ip/commit/89d7ff4c994f50aee13bef075f37f90ed30c95d5 change extract last ip from `x-forwarded-for`, bud client ip is first, spec: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For. For me this broke my app.

**Comment by pbojinov** [comment]
Sorry about that. I'm going to revert this change tonight and push up a new version. Will let you know shortly.

**Comment by sidan5** [comment]
Breaks my app too.

**Comment by sidan5** [comment]
@pbojinov When this is going to be resolved? Thanks!

**Comment by ss-tombrown** [comment]
This breaks our app too!
