### ISSUE TITLE
Incompatible with Next.js middleware/Vercel edge functions

### ISSUE THREAD

**Issue by richardweaver** [pbojinov/request-ip#63]
I'm using the library to enable IP whitelisting for a Next.js app hosted on Vercel. This causes a build error:

```
Failed to compile.

../../node_modules/is_js/is.js
Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Middleware middleware

Import trace for requested module:
../../node_modules/request-ip/dist/index.js
./middleware.ts
```

This is this module's only dependency, can this import be dropped in favour of lightweight equivalents?

**Comment by pbojinov** [comment]
We can definitely drop the dependency in favor or a lightweight equivalent. Thanks for submitting the PR, I'll take a look.

**Comment by pbojinov** [comment]
Resolved in https://github.com/pbojinov/request-ip/issues/63
