### ISSUE TITLE
Error: Cannot find module './is'

### ISSUE THREAD

**Issue by hungtcs** [pbojinov/request-ip#65]
version `3.1.0 ` missing `is.js` in dist folder

![image](https://user-images.githubusercontent.com/11692935/177488348-f3c8b7a4-d9b3-4f7f-89e9-f146e014cdb1.png)

**Comment by AliSaberi** [comment]
I have the same issue !!!

**Comment by hungtcs** [comment]
I am now back to 3.0.2, and 3.0.2 uses an external npm package

https://github.com/pbojinov/request-ip/blob/a2f411bd546e3f07b0bb702a958d955bef84a461/dist/index.js#L5

Looks like forgot to modify the build command

https://github.com/pbojinov/request-ip/blob/d1219037770b6707bf88d38beb866a6a0012c90a/package.json#L54

**Comment by enricoros** [comment]
+1 Same issue. Production borken 🤦

**Comment by perrin4869** [comment]
maybe best to remove babel from this repo? don't see any features that need transpiling these days

**Comment by jblyberg** [comment]
+1

**Comment by pbojinov** [comment]
I'll fix this tonight, sorry everyone

**Comment by pbojinov** [comment]
> maybe best to remove babel from this repo? don't see any features that need transpiling these days

That's a good point. I had added Babel over 4 years ago when none of the ES6 features were in Node. It's probably not needed.

**Comment by pbojinov** [comment]
Released 3.2.0 with an updated build file. Let me know if this works for everyone.

**Comment by xiazhichen1** [comment]
Upgrading to 3.2.0 gives me: Error: Cannot find module '\node_modules\request-ip\lib\index.js'. Please verify that the package.json has a valid "main" entry

I have tried deleted node_modules and reinstall but still the same error.

**Comment by hungtcs** [comment]
Need to include lib folder in package.json `files` entry

https://github.com/pbojinov/request-ip/blob/3feaa1356a7877a28c4b49b53a98209d481caa8f/package.json#L49-L51

**Comment by pbojinov** [comment]
Thank you for that! Just added that to 3.3.0 and tested it locally. It's working without throwing any errors. 

<img width="874" alt="image" src="https://user-images.githubusercontent.com/709616/177693406-fe0677dd-57f2-4019-ac0c-9dffa47161f5.png">
