### ISSUE TITLE
needs semver

### ISSUE THREAD

**Issue by coolaj86** [pbojinov/request-ip#7]
Will you just bump this to 1.0.0 please?

It appears that the API is production ready and I would like the security of knowing that until 2.0.0 I don't need to worry that the single API is going to break or disappear.

Thanks.

**Comment by pbojinov** [comment]
good call, that sounds good to me :+1:

**Comment by pbojinov** [comment]
fixed in #8, thank you

**Comment by coolaj86** [comment]
No, thank you!
